services:
  - type: web
    name: salarite-backend
    env: python
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: salarite-frontend
    env: node
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://salarite.onrender.com
      - key: VITE_SOCKET_URL
        value: https://salarite.onrender.com