services:
  - type: web
    name: salarite-backend
    env: python
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:socket_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://salarite_database_user:3p7h1qv57lj7knDn7ITlRTZTbo9FfgPr@dpg-d7k7p0e7r5hc73fts8a0-a/salarite_database
      - key: FRONTEND_URL
        value: https://salarite-frontend-ultw.onrender.com
 
  - type: web
    name: salarite-frontend
    env: node
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://salarite.onrender.com
      - key: VITE_SOCKET_URL
        value: https://salarite.onrender.com